# Generated by Django 5.0.2 on 2024-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.TextField()),
                ('new_text', models.TextField()),
                ('new_image_url', models.URLField()),
                ('new_publish_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
