# Generated by Django 5.0.2 on 2024-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='new_image_url',
            field=models.TextField(),
        ),
    ]
