# Generated by Django 5.0.2 on 2024-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_rename_new_image_url_news_new_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_tag',
            field=models.CharField(default='None'),
            preserve_default=False,
        ),
    ]
