# Generated by Django 5.0.2 on 2024-05-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_news_new_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_summery',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='new_tag',
            field=models.TextField(),
        ),
    ]
